services:
  - type: web
    name: transbook
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: transbook-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPLIT_DOMAINS
        sync: false
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPL_ID
        value: cloud-deployment

databases:
  - name: transbook-db
    databaseName: transbook
    user: transbook